### ISSUE TITLE
anki2.1.35 support

### ISSUE THREAD

**Issue by freemedom** [feilongfl/ankiview-vscode#26]
![image](https://github.com/feilongfl/ankiview-vscode/assets/57294686/79763bae-2566-4eff-a5d3-b5bf948d8f33)

**Comment by feilongfl** [comment]
我想我需要更多的信息来确认这个问题：

1. 想确认下您使用的版本
![image](https://github.com/feilongfl/ankiview-vscode/assets/10269596/7b73891f-2328-4024-af49-68507d2d93b4)

2. 希望能共享下您使用的牌组，或者您使用其他牌组也会遇到同样问题么？

3. 确认下您是按照如下步骤操作的么？
  - ![image](https://github.com/feilongfl/ankiview-vscode/assets/10269596/603822c4-74c5-44c5-aac6-c56835ff90dd)
  - ![image](https://github.com/feilongfl/ankiview-vscode/assets/10269596/81de9fad-6495-48dd-a4ad-b224e54204b0)
  - ![image](https://github.com/feilongfl/ankiview-vscode/assets/10269596/9c09be87-37c2-46e3-b8a3-8ff9ad39678e)
  - 点击后回到主菜单？ ![image](https://github.com/feilongfl/ankiview-vscode/assets/10269596/50b818ce-9884-457d-ba01-4e78d6480ffc)

**Comment by freemedom** [comment]
我开新电脑测试一下

**Comment by freemedom** [comment]
![image](https://github.com/feilongfl/ankiview-vscode/assets/57294686/ed8f2ed0-67f9-4fd3-ade4-371c19e2a345)
我没有这个界面

**Comment by freemedom** [comment]
开新虚拟机又测试了下，确实还是有这个问题
应该不是牌组的问题，我新安anki，建张卡，也是这样
是0.0.7
怀疑是我anki版本2.1.35的问题，等会我安新版本anki再试试

**Comment by feilongfl** [comment]
> 开新虚拟机又测试了下，确实还是有这个问题 应该不是牌组的问题，我新安anki，建张卡，也是这样 是0.0.7 怀疑是我anki版本2.1.35的问题，等会我安新版本anki再试试

2.1.35的anki没有测试过，我去看了下anki的发布记录，这是一个三年前的版本，目前的我使用的是2.1.65

![image](https://github.com/feilongfl/ankiview-vscode/assets/10269596/a7082140-be9d-47ac-9114-1778d36e1402)

详细版本号供您参考：
![image](https://github.com/feilongfl/ankiview-vscode/assets/10269596/19694e0f-cbab-4003-bf69-291932fd7cfa)

**Comment by freemedom** [comment]
试了下2.1.65，能正常用了，大概是ankiconnect的机制有变化？不知道大佬有没有空适配一下35版本，不行的话我自己研究一下适配吧，我有几个插件新版不能用了，所以一直停在了35版本

**Comment by freemedom** [comment]
~~我试着调试了下，但是不知道为什么，点Run Extension后，扩展开发宿主的explorer里的open deck那个栏也显示不出来了~~

**Comment by freemedom** [comment]
`let card = await this._ankiConnect.api.graphical.guiCurrentCard();`
card的值是下面这些，您看看有没有什么问题

```
{
  result: {
    cardId: 1691636763303,
    fields: {
      Front: {
        value: "666",
        order: 0,
      },
      Back: {
        value: "777",
        order: 1,
      },
    },
    fieldOrder: 0,
    question: "<style>.card {\n  font-family: arial;\n  font-size: 20px;\n  text-align: center;\n  color: black;\n  background-color: white;\n}\n</style>666",
    answer: "<style>.card {\n  font-family: arial;\n  font-size: 20px;\n  text-align: center;\n  color: black;\n  background-color: white;\n}\n</style>666\n\n<hr id=answer>\n\n777",
    buttons: [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
    ],
    nextReviews: [
      "⁨6⁩h",
      "⁨1⁩d",
      "⁨2⁩d",
      "⁨4⁩d",
      "⁨2⁩d",
      "⁨2⁩d",
      "⁨2⁩d",
    ],
    modelName: "Basic-b01ef",
    deckName: "a test",
    css: ".card {\n  font-family: arial;\n  font-size: 20px;\n  text-align: center;\n  color: black;\n  background-color: white;\n}\n",
    template: "Card 1",
  },
  error: null,
}
```

**Comment by freemedom** [comment]
public async get() {
        try {
            let deckStat = await this._ankiConnect.api.deck.getDeckStat(this.label);
我这里deckStat是undefined，或许是这里的问题？

**Comment by feilongfl** [comment]
> ```
> public async get() {
>     try {
>         let deckStat = await this._ankiConnect.api.deck.getDeckStat(this.label);
> ```
> 
> 我这里deckStat是undefined，或许是这里的问题？

确实是这里问题， 2.1.35版本对此命令的回复是`unsupported action`
[这个](https://foosoft.net/projects/anki-connect/#:~:text=getDeckStats,-Gets%20statistics%20such)命令用于展示任务栏的学习状态

![image](https://github.com/feilongfl/ankiview-vscode/assets/10269596/2f1fba3e-2e16-4036-8c01-3d593e15cf46)


```
0000   2c f0 5d ae 64 3e 08 00 27 be 54 d9 08 00 45 00   ,.].d>..'.T...E.
0010   00 e7 59 17 40 00 80 06 0a c9 c0 a8 0a 7c c0 a8   ..Y.@........|..
0020   0a 64 22 3d 9e 8c cd 4e 88 7f 34 a8 7f 47 50 18   .d"=...N..4..GP.
0030   20 14 17 fe 00 00 48 54 54 50 2f 31 2e 31 20 32    .....HTTP/1.1 2
0040   30 30 20 4f 4b 0d 0a 43 6f 6e 74 65 6e 74 2d 54   00 OK..Content-T
0050   79 70 65 3a 20 74 65 78 74 2f 6a 73 6f 6e 0d 0a   ype: text/json..
0060   41 63 63 65 73 73 2d 43 6f 6e 74 72 6f 6c 2d 41   Access-Control-A
0070   6c 6c 6f 77 2d 4f 72 69 67 69 6e 3a 20 68 74 74   llow-Origin: htt
0080   70 3a 2f 2f 6c 6f 63 61 6c 68 6f 73 74 0d 0a 41   p://localhost..A
0090   63 63 65 73 73 2d 43 6f 6e 74 72 6f 6c 2d 41 6c   ccess-Control-Al
00a0   6c 6f 77 2d 48 65 61 64 65 72 73 3a 20 2a 0d 0a   low-Headers: *..
00b0   43 6f 6e 74 65 6e 74 2d 4c 65 6e 67 74 68 3a 20   Content-Length: 
00c0   34 37 0d 0a 0d 0a 7b 22 72 65 73 75 6c 74 22 3a   47....{"result":
00d0   20 6e 75 6c 6c 2c 20 22 65 72 72 6f 72 22 3a 20    null, "error": 
00e0   22 75 6e 73 75 70 70 6f 72 74 65 64 20 61 63 74   "unsupported act
00f0   69 6f 6e 22 7d                                    ion"}

```

**Comment by feilongfl** [comment]
我想这个问题在 [v0.0.8](https://github.com/feilongfl/ankiview-vscode/releases/tag/0.0.8) 中已经解决，
我增加了这里对于unsupport的异常处理，
当getDeckStats错误时，继续运行，
但是会导致学习状态在使用低版本anki时无法显示。

如果没有解决，请重新打开这个issues

---

因为微软token过期了，所以流水线失败
已经手动上传这个版本到微软商店。
OVSX不受影响

**Comment by freemedom** [comment]
多谢，可以了
